// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/delyke/gophermat_bonus_system/internal/model"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/delyke/gophermat_bonus_system/internal/repository"
)

// BonusRepository is an autogenerated mock type for the BonusRepository type
type BonusRepository struct {
	mock.Mock
}

type BonusRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *BonusRepository) EXPECT() *BonusRepository_Expecter {
	return &BonusRepository_Expecter{mock: &_m.Mock}
}

// CreateWithdrawalWithBalance provides a mock function with given fields: ctx, withdrawal
func (_m *BonusRepository) CreateWithdrawalWithBalance(ctx context.Context, withdrawal *model.Withdrawal) error {
	ret := _m.Called(ctx, withdrawal)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithdrawalWithBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Withdrawal) error); ok {
		r0 = rf(ctx, withdrawal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BonusRepository_CreateWithdrawalWithBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithdrawalWithBalance'
type BonusRepository_CreateWithdrawalWithBalance_Call struct {
	*mock.Call
}

// CreateWithdrawalWithBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - withdrawal *model.Withdrawal
func (_e *BonusRepository_Expecter) CreateWithdrawalWithBalance(ctx interface{}, withdrawal interface{}) *BonusRepository_CreateWithdrawalWithBalance_Call {
	return &BonusRepository_CreateWithdrawalWithBalance_Call{Call: _e.mock.On("CreateWithdrawalWithBalance", ctx, withdrawal)}
}

func (_c *BonusRepository_CreateWithdrawalWithBalance_Call) Run(run func(ctx context.Context, withdrawal *model.Withdrawal)) *BonusRepository_CreateWithdrawalWithBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Withdrawal))
	})
	return _c
}

func (_c *BonusRepository_CreateWithdrawalWithBalance_Call) Return(_a0 error) *BonusRepository_CreateWithdrawalWithBalance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BonusRepository_CreateWithdrawalWithBalance_Call) RunAndReturn(run func(context.Context, *model.Withdrawal) error) *BonusRepository_CreateWithdrawalWithBalance_Call {
	_c.Call.Return(run)
	return _c
}

// Orders provides a mock function with no fields
func (_m *BonusRepository) Orders() repository.OrderRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Orders")
	}

	var r0 repository.OrderRepository
	if rf, ok := ret.Get(0).(func() repository.OrderRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.OrderRepository)
		}
	}

	return r0
}

// BonusRepository_Orders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Orders'
type BonusRepository_Orders_Call struct {
	*mock.Call
}

// Orders is a helper method to define mock.On call
func (_e *BonusRepository_Expecter) Orders() *BonusRepository_Orders_Call {
	return &BonusRepository_Orders_Call{Call: _e.mock.On("Orders")}
}

func (_c *BonusRepository_Orders_Call) Run(run func()) *BonusRepository_Orders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BonusRepository_Orders_Call) Return(_a0 repository.OrderRepository) *BonusRepository_Orders_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BonusRepository_Orders_Call) RunAndReturn(run func() repository.OrderRepository) *BonusRepository_Orders_Call {
	_c.Call.Return(run)
	return _c
}

// Users provides a mock function with no fields
func (_m *BonusRepository) Users() repository.UserRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Users")
	}

	var r0 repository.UserRepository
	if rf, ok := ret.Get(0).(func() repository.UserRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.UserRepository)
		}
	}

	return r0
}

// BonusRepository_Users_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Users'
type BonusRepository_Users_Call struct {
	*mock.Call
}

// Users is a helper method to define mock.On call
func (_e *BonusRepository_Expecter) Users() *BonusRepository_Users_Call {
	return &BonusRepository_Users_Call{Call: _e.mock.On("Users")}
}

func (_c *BonusRepository_Users_Call) Run(run func()) *BonusRepository_Users_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BonusRepository_Users_Call) Return(_a0 repository.UserRepository) *BonusRepository_Users_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BonusRepository_Users_Call) RunAndReturn(run func() repository.UserRepository) *BonusRepository_Users_Call {
	_c.Call.Return(run)
	return _c
}

// Withdrawals provides a mock function with no fields
func (_m *BonusRepository) Withdrawals() repository.WithdrawalRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Withdrawals")
	}

	var r0 repository.WithdrawalRepository
	if rf, ok := ret.Get(0).(func() repository.WithdrawalRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.WithdrawalRepository)
		}
	}

	return r0
}

// BonusRepository_Withdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdrawals'
type BonusRepository_Withdrawals_Call struct {
	*mock.Call
}

// Withdrawals is a helper method to define mock.On call
func (_e *BonusRepository_Expecter) Withdrawals() *BonusRepository_Withdrawals_Call {
	return &BonusRepository_Withdrawals_Call{Call: _e.mock.On("Withdrawals")}
}

func (_c *BonusRepository_Withdrawals_Call) Run(run func()) *BonusRepository_Withdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BonusRepository_Withdrawals_Call) Return(_a0 repository.WithdrawalRepository) *BonusRepository_Withdrawals_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BonusRepository_Withdrawals_Call) RunAndReturn(run func() repository.WithdrawalRepository) *BonusRepository_Withdrawals_Call {
	_c.Call.Return(run)
	return _c
}

// NewBonusRepository creates a new instance of BonusRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBonusRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BonusRepository {
	mock := &BonusRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
