// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/delyke/gophermat_bonus_system/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, login, password
func (_m *UserRepository) Create(ctx context.Context, login string, password string) (*model.User, error) {
	ret := _m.Called(ctx, login, password)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.User, error)); ok {
		return rf(ctx, login, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.User); ok {
		r0 = rf(ctx, login, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, login, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - password string
func (_e *UserRepository_Expecter) Create(ctx interface{}, login interface{}, password interface{}) *UserRepository_Create_Call {
	return &UserRepository_Create_Call{Call: _e.mock.On("Create", ctx, login, password)}
}

func (_c *UserRepository_Create_Call) Run(run func(ctx context.Context, login string, password string)) *UserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *UserRepository_Create_Call) Return(_a0 *model.User, _a1 error) *UserRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_Create_Call) RunAndReturn(run func(context.Context, string, string) (*model.User, error)) *UserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalanceByUUID provides a mock function with given fields: ctx, _a1
func (_m *UserRepository) GetBalanceByUUID(ctx context.Context, _a1 uuid.UUID) (float64, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetBalanceByUUID")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (float64, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) float64); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetBalanceByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalanceByUUID'
type UserRepository_GetBalanceByUUID_Call struct {
	*mock.Call
}

// GetBalanceByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 uuid.UUID
func (_e *UserRepository_Expecter) GetBalanceByUUID(ctx interface{}, _a1 interface{}) *UserRepository_GetBalanceByUUID_Call {
	return &UserRepository_GetBalanceByUUID_Call{Call: _e.mock.On("GetBalanceByUUID", ctx, _a1)}
}

func (_c *UserRepository_GetBalanceByUUID_Call) Run(run func(ctx context.Context, _a1 uuid.UUID)) *UserRepository_GetBalanceByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *UserRepository_GetBalanceByUUID_Call) Return(_a0 float64, _a1 error) *UserRepository_GetBalanceByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_GetBalanceByUUID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (float64, error)) *UserRepository_GetBalanceByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByLogin provides a mock function with given fields: ctx, login
func (_m *UserRepository) GetByLogin(ctx context.Context, login string) (*model.User, error) {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for GetByLogin")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByLogin'
type UserRepository_GetByLogin_Call struct {
	*mock.Call
}

// GetByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *UserRepository_Expecter) GetByLogin(ctx interface{}, login interface{}) *UserRepository_GetByLogin_Call {
	return &UserRepository_GetByLogin_Call{Call: _e.mock.On("GetByLogin", ctx, login)}
}

func (_c *UserRepository_GetByLogin_Call) Run(run func(ctx context.Context, login string)) *UserRepository_GetByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepository_GetByLogin_Call) Return(_a0 *model.User, _a1 error) *UserRepository_GetByLogin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_GetByLogin_Call) RunAndReturn(run func(context.Context, string) (*model.User, error)) *UserRepository_GetByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// SetBalanceByUUID provides a mock function with given fields: ctx, _a1, amount
func (_m *UserRepository) SetBalanceByUUID(ctx context.Context, _a1 uuid.UUID, amount float64) error {
	ret := _m.Called(ctx, _a1, amount)

	if len(ret) == 0 {
		panic("no return value specified for SetBalanceByUUID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, float64) error); ok {
		r0 = rf(ctx, _a1, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepository_SetBalanceByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBalanceByUUID'
type UserRepository_SetBalanceByUUID_Call struct {
	*mock.Call
}

// SetBalanceByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 uuid.UUID
//   - amount float64
func (_e *UserRepository_Expecter) SetBalanceByUUID(ctx interface{}, _a1 interface{}, amount interface{}) *UserRepository_SetBalanceByUUID_Call {
	return &UserRepository_SetBalanceByUUID_Call{Call: _e.mock.On("SetBalanceByUUID", ctx, _a1, amount)}
}

func (_c *UserRepository_SetBalanceByUUID_Call) Run(run func(ctx context.Context, _a1 uuid.UUID, amount float64)) *UserRepository_SetBalanceByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(float64))
	})
	return _c
}

func (_c *UserRepository_SetBalanceByUUID_Call) Return(_a0 error) *UserRepository_SetBalanceByUUID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepository_SetBalanceByUUID_Call) RunAndReturn(run func(context.Context, uuid.UUID, float64) error) *UserRepository_SetBalanceByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
