// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/delyke/gophermat_bonus_system/internal/model"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, order
func (_m *OrderRepository) Create(ctx context.Context, order *model.Order) (*model.Order, error) {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Order) (*model.Order, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Order) *model.Order); ok {
		r0 = rf(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Order) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OrderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - order *model.Order
func (_e *OrderRepository_Expecter) Create(ctx interface{}, order interface{}) *OrderRepository_Create_Call {
	return &OrderRepository_Create_Call{Call: _e.mock.On("Create", ctx, order)}
}

func (_c *OrderRepository_Create_Call) Run(run func(ctx context.Context, order *model.Order)) *OrderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Order))
	})
	return _c
}

func (_c *OrderRepository_Create_Call) Return(_a0 *model.Order, _a1 error) *OrderRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Order) (*model.Order, error)) *OrderRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByNumber provides a mock function with given fields: ctx, number
func (_m *OrderRepository) GetByNumber(ctx context.Context, number string) (*model.Order, error) {
	ret := _m.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for GetByNumber")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Order, error)); ok {
		return rf(ctx, number)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Order); ok {
		r0 = rf(ctx, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_GetByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByNumber'
type OrderRepository_GetByNumber_Call struct {
	*mock.Call
}

// GetByNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - number string
func (_e *OrderRepository_Expecter) GetByNumber(ctx interface{}, number interface{}) *OrderRepository_GetByNumber_Call {
	return &OrderRepository_GetByNumber_Call{Call: _e.mock.On("GetByNumber", ctx, number)}
}

func (_c *OrderRepository_GetByNumber_Call) Run(run func(ctx context.Context, number string)) *OrderRepository_GetByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderRepository_GetByNumber_Call) Return(_a0 *model.Order, _a1 error) *OrderRepository_GetByNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_GetByNumber_Call) RunAndReturn(run func(context.Context, string) (*model.Order, error)) *OrderRepository_GetByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetListByUploadedDesc provides a mock function with given fields: ctx, userUUID
func (_m *OrderRepository) GetListByUploadedDesc(ctx context.Context, userUUID uuid.UUID) ([]*model.Order, error) {
	ret := _m.Called(ctx, userUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetListByUploadedDesc")
	}

	var r0 []*model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.Order, error)); ok {
		return rf(ctx, userUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.Order); ok {
		r0 = rf(ctx, userUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_GetListByUploadedDesc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetListByUploadedDesc'
type OrderRepository_GetListByUploadedDesc_Call struct {
	*mock.Call
}

// GetListByUploadedDesc is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID uuid.UUID
func (_e *OrderRepository_Expecter) GetListByUploadedDesc(ctx interface{}, userUUID interface{}) *OrderRepository_GetListByUploadedDesc_Call {
	return &OrderRepository_GetListByUploadedDesc_Call{Call: _e.mock.On("GetListByUploadedDesc", ctx, userUUID)}
}

func (_c *OrderRepository_GetListByUploadedDesc_Call) Run(run func(ctx context.Context, userUUID uuid.UUID)) *OrderRepository_GetListByUploadedDesc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *OrderRepository_GetListByUploadedDesc_Call) Return(_a0 []*model.Order, _a1 error) *OrderRepository_GetListByUploadedDesc_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_GetListByUploadedDesc_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.Order, error)) *OrderRepository_GetListByUploadedDesc_Call {
	_c.Call.Return(run)
	return _c
}

// ListPending provides a mock function with given fields: ctx, limit
func (_m *OrderRepository) ListPending(ctx context.Context, limit uint64) ([]*model.Order, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListPending")
	}

	var r0 []*model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]*model.Order, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []*model.Order); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_ListPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPending'
type OrderRepository_ListPending_Call struct {
	*mock.Call
}

// ListPending is a helper method to define mock.On call
//   - ctx context.Context
//   - limit uint64
func (_e *OrderRepository_Expecter) ListPending(ctx interface{}, limit interface{}) *OrderRepository_ListPending_Call {
	return &OrderRepository_ListPending_Call{Call: _e.mock.On("ListPending", ctx, limit)}
}

func (_c *OrderRepository_ListPending_Call) Run(run func(ctx context.Context, limit uint64)) *OrderRepository_ListPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *OrderRepository_ListPending_Call) Return(_a0 []*model.Order, _a1 error) *OrderRepository_ListPending_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_ListPending_Call) RunAndReturn(run func(context.Context, uint64) ([]*model.Order, error)) *OrderRepository_ListPending_Call {
	_c.Call.Return(run)
	return _c
}

// ListPendingAfter provides a mock function with given fields: ctx, limit, afterUploadedAt, afterUUID
func (_m *OrderRepository) ListPendingAfter(ctx context.Context, limit uint64, afterUploadedAt time.Time, afterUUID uuid.UUID) ([]*model.Order, error) {
	ret := _m.Called(ctx, limit, afterUploadedAt, afterUUID)

	if len(ret) == 0 {
		panic("no return value specified for ListPendingAfter")
	}

	var r0 []*model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, time.Time, uuid.UUID) ([]*model.Order, error)); ok {
		return rf(ctx, limit, afterUploadedAt, afterUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, time.Time, uuid.UUID) []*model.Order); ok {
		r0 = rf(ctx, limit, afterUploadedAt, afterUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, time.Time, uuid.UUID) error); ok {
		r1 = rf(ctx, limit, afterUploadedAt, afterUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_ListPendingAfter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPendingAfter'
type OrderRepository_ListPendingAfter_Call struct {
	*mock.Call
}

// ListPendingAfter is a helper method to define mock.On call
//   - ctx context.Context
//   - limit uint64
//   - afterUploadedAt time.Time
//   - afterUUID uuid.UUID
func (_e *OrderRepository_Expecter) ListPendingAfter(ctx interface{}, limit interface{}, afterUploadedAt interface{}, afterUUID interface{}) *OrderRepository_ListPendingAfter_Call {
	return &OrderRepository_ListPendingAfter_Call{Call: _e.mock.On("ListPendingAfter", ctx, limit, afterUploadedAt, afterUUID)}
}

func (_c *OrderRepository_ListPendingAfter_Call) Run(run func(ctx context.Context, limit uint64, afterUploadedAt time.Time, afterUUID uuid.UUID)) *OrderRepository_ListPendingAfter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(time.Time), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *OrderRepository_ListPendingAfter_Call) Return(_a0 []*model.Order, _a1 error) *OrderRepository_ListPendingAfter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_ListPendingAfter_Call) RunAndReturn(run func(context.Context, uint64, time.Time, uuid.UUID) ([]*model.Order, error)) *OrderRepository_ListPendingAfter_Call {
	_c.Call.Return(run)
	return _c
}

// SetAccrualByUUID provides a mock function with given fields: ctx, _a1, accrual
func (_m *OrderRepository) SetAccrualByUUID(ctx context.Context, _a1 uuid.UUID, accrual float64) error {
	ret := _m.Called(ctx, _a1, accrual)

	if len(ret) == 0 {
		panic("no return value specified for SetAccrualByUUID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, float64) error); ok {
		r0 = rf(ctx, _a1, accrual)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_SetAccrualByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAccrualByUUID'
type OrderRepository_SetAccrualByUUID_Call struct {
	*mock.Call
}

// SetAccrualByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 uuid.UUID
//   - accrual float64
func (_e *OrderRepository_Expecter) SetAccrualByUUID(ctx interface{}, _a1 interface{}, accrual interface{}) *OrderRepository_SetAccrualByUUID_Call {
	return &OrderRepository_SetAccrualByUUID_Call{Call: _e.mock.On("SetAccrualByUUID", ctx, _a1, accrual)}
}

func (_c *OrderRepository_SetAccrualByUUID_Call) Run(run func(ctx context.Context, _a1 uuid.UUID, accrual float64)) *OrderRepository_SetAccrualByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(float64))
	})
	return _c
}

func (_c *OrderRepository_SetAccrualByUUID_Call) Return(_a0 error) *OrderRepository_SetAccrualByUUID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_SetAccrualByUUID_Call) RunAndReturn(run func(context.Context, uuid.UUID, float64) error) *OrderRepository_SetAccrualByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// SetStatusByUUID provides a mock function with given fields: ctx, _a1, status
func (_m *OrderRepository) SetStatusByUUID(ctx context.Context, _a1 uuid.UUID, status model.OrderStatus) error {
	ret := _m.Called(ctx, _a1, status)

	if len(ret) == 0 {
		panic("no return value specified for SetStatusByUUID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.OrderStatus) error); ok {
		r0 = rf(ctx, _a1, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_SetStatusByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatusByUUID'
type OrderRepository_SetStatusByUUID_Call struct {
	*mock.Call
}

// SetStatusByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 uuid.UUID
//   - status model.OrderStatus
func (_e *OrderRepository_Expecter) SetStatusByUUID(ctx interface{}, _a1 interface{}, status interface{}) *OrderRepository_SetStatusByUUID_Call {
	return &OrderRepository_SetStatusByUUID_Call{Call: _e.mock.On("SetStatusByUUID", ctx, _a1, status)}
}

func (_c *OrderRepository_SetStatusByUUID_Call) Run(run func(ctx context.Context, _a1 uuid.UUID, status model.OrderStatus)) *OrderRepository_SetStatusByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.OrderStatus))
	})
	return _c
}

func (_c *OrderRepository_SetStatusByUUID_Call) Return(_a0 error) *OrderRepository_SetStatusByUUID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_SetStatusByUUID_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.OrderStatus) error) *OrderRepository_SetStatusByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
