// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/delyke/gophermat_bonus_system/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// WithdrawalRepository is an autogenerated mock type for the WithdrawalRepository type
type WithdrawalRepository struct {
	mock.Mock
}

type WithdrawalRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *WithdrawalRepository) EXPECT() *WithdrawalRepository_Expecter {
	return &WithdrawalRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, withdrawal
func (_m *WithdrawalRepository) Create(ctx context.Context, withdrawal *model.Withdrawal) error {
	ret := _m.Called(ctx, withdrawal)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Withdrawal) error); ok {
		r0 = rf(ctx, withdrawal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithdrawalRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type WithdrawalRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - withdrawal *model.Withdrawal
func (_e *WithdrawalRepository_Expecter) Create(ctx interface{}, withdrawal interface{}) *WithdrawalRepository_Create_Call {
	return &WithdrawalRepository_Create_Call{Call: _e.mock.On("Create", ctx, withdrawal)}
}

func (_c *WithdrawalRepository_Create_Call) Run(run func(ctx context.Context, withdrawal *model.Withdrawal)) *WithdrawalRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Withdrawal))
	})
	return _c
}

func (_c *WithdrawalRepository_Create_Call) Return(_a0 error) *WithdrawalRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WithdrawalRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Withdrawal) error) *WithdrawalRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserByDateDesc provides a mock function with given fields: ctx, userUUID
func (_m *WithdrawalRepository) ListByUserByDateDesc(ctx context.Context, userUUID uuid.UUID) ([]*model.Withdrawal, error) {
	ret := _m.Called(ctx, userUUID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserByDateDesc")
	}

	var r0 []*model.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.Withdrawal, error)); ok {
		return rf(ctx, userUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.Withdrawal); ok {
		r0 = rf(ctx, userUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Withdrawal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithdrawalRepository_ListByUserByDateDesc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserByDateDesc'
type WithdrawalRepository_ListByUserByDateDesc_Call struct {
	*mock.Call
}

// ListByUserByDateDesc is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID uuid.UUID
func (_e *WithdrawalRepository_Expecter) ListByUserByDateDesc(ctx interface{}, userUUID interface{}) *WithdrawalRepository_ListByUserByDateDesc_Call {
	return &WithdrawalRepository_ListByUserByDateDesc_Call{Call: _e.mock.On("ListByUserByDateDesc", ctx, userUUID)}
}

func (_c *WithdrawalRepository_ListByUserByDateDesc_Call) Run(run func(ctx context.Context, userUUID uuid.UUID)) *WithdrawalRepository_ListByUserByDateDesc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *WithdrawalRepository_ListByUserByDateDesc_Call) Return(_a0 []*model.Withdrawal, _a1 error) *WithdrawalRepository_ListByUserByDateDesc_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WithdrawalRepository_ListByUserByDateDesc_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.Withdrawal, error)) *WithdrawalRepository_ListByUserByDateDesc_Call {
	_c.Call.Return(run)
	return _c
}

// SumAmountByUserUUID provides a mock function with given fields: ctx, userUUID
func (_m *WithdrawalRepository) SumAmountByUserUUID(ctx context.Context, userUUID uuid.UUID) (float64, error) {
	ret := _m.Called(ctx, userUUID)

	if len(ret) == 0 {
		panic("no return value specified for SumAmountByUserUUID")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (float64, error)); ok {
		return rf(ctx, userUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) float64); ok {
		r0 = rf(ctx, userUUID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithdrawalRepository_SumAmountByUserUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumAmountByUserUUID'
type WithdrawalRepository_SumAmountByUserUUID_Call struct {
	*mock.Call
}

// SumAmountByUserUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID uuid.UUID
func (_e *WithdrawalRepository_Expecter) SumAmountByUserUUID(ctx interface{}, userUUID interface{}) *WithdrawalRepository_SumAmountByUserUUID_Call {
	return &WithdrawalRepository_SumAmountByUserUUID_Call{Call: _e.mock.On("SumAmountByUserUUID", ctx, userUUID)}
}

func (_c *WithdrawalRepository_SumAmountByUserUUID_Call) Run(run func(ctx context.Context, userUUID uuid.UUID)) *WithdrawalRepository_SumAmountByUserUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *WithdrawalRepository_SumAmountByUserUUID_Call) Return(_a0 float64, _a1 error) *WithdrawalRepository_SumAmountByUserUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WithdrawalRepository_SumAmountByUserUUID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (float64, error)) *WithdrawalRepository_SumAmountByUserUUID_Call {
	_c.Call.Return(run)
	return _c
}

// NewWithdrawalRepository creates a new instance of WithdrawalRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWithdrawalRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WithdrawalRepository {
	mock := &WithdrawalRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
