// Code generated by ogen, DO NOT EDIT.

package accrual_v1

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetOrderInfoParams is parameters of GetOrderInfo operation.
type GetOrderInfoParams struct {
	// Номер заказа, для которого запрашиваются данные о
	// начислении бонусных баллов.
	Number string
}

func unpackGetOrderInfoParams(packed middleware.Parameters) (params GetOrderInfoParams) {
	{
		key := middleware.ParameterKey{
			Name: "number",
			In:   "path",
		}
		params.Number = packed[key].(string)
	}
	return params
}

func decodeGetOrderInfoParams(args [1]string, argsEscaped bool, r *http.Request) (params GetOrderInfoParams, _ error) {
	// Decode path: number.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "number",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Number = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "number",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
