// Code generated by ogen, DO NOT EDIT.

package accrual_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetOrderInfo implements GetOrderInfo operation.
	//
	// Получение информации о расчете начислений баллов
	// лояльности.
	//
	// GET /api/orders/{number}
	GetOrderInfo(ctx context.Context, params GetOrderInfoParams) (GetOrderInfoRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
