// Code generated by ogen, DO NOT EDIT.

package accrual_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetOrderInfo implements GetOrderInfo operation.
//
// Получение информации о расчете начислений баллов
// лояльности.
//
// GET /api/orders/{number}
func (UnimplementedHandler) GetOrderInfo(ctx context.Context, params GetOrderInfoParams) (r GetOrderInfoRes, _ error) {
	return r, ht.ErrNotImplemented
}
