// Code generated by ogen, DO NOT EDIT.

package accrual_v1

import (
	"io"

	"github.com/go-faster/errors"
)

// GetOrderInfoInternalServerError is response for GetOrderInfo operation.
type GetOrderInfoInternalServerError struct{}

func (*GetOrderInfoInternalServerError) getOrderInfoRes() {}

// GetOrderInfoNoContent is response for GetOrderInfo operation.
type GetOrderInfoNoContent struct{}

func (*GetOrderInfoNoContent) getOrderInfoRes() {}

// Ref: #/components/schemas/get_order_info_response
type GetOrderInfoResponse struct {
	// Номер заказа.
	Order  string      `json:"order"`
	Status OrderStatus `json:"status"`
	// Рассчитанные баллы к начислению, при отсутствии
	// начисления - поле отсутствует в ответе.
	Accrual OptFloat32 `json:"accrual"`
}

// GetOrder returns the value of Order.
func (s *GetOrderInfoResponse) GetOrder() string {
	return s.Order
}

// GetStatus returns the value of Status.
func (s *GetOrderInfoResponse) GetStatus() OrderStatus {
	return s.Status
}

// GetAccrual returns the value of Accrual.
func (s *GetOrderInfoResponse) GetAccrual() OptFloat32 {
	return s.Accrual
}

// SetOrder sets the value of Order.
func (s *GetOrderInfoResponse) SetOrder(val string) {
	s.Order = val
}

// SetStatus sets the value of Status.
func (s *GetOrderInfoResponse) SetStatus(val OrderStatus) {
	s.Status = val
}

// SetAccrual sets the value of Accrual.
func (s *GetOrderInfoResponse) SetAccrual(val OptFloat32) {
	s.Accrual = val
}

func (*GetOrderInfoResponse) getOrderInfoRes() {}

type GetOrderInfoTooManyRequests struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetOrderInfoTooManyRequests) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

// GetOrderInfoTooManyRequestsHeaders wraps GetOrderInfoTooManyRequests with response headers.
type GetOrderInfoTooManyRequestsHeaders struct {
	RetryAfter OptInt
	Response   GetOrderInfoTooManyRequests
}

// GetRetryAfter returns the value of RetryAfter.
func (s *GetOrderInfoTooManyRequestsHeaders) GetRetryAfter() OptInt {
	return s.RetryAfter
}

// GetResponse returns the value of Response.
func (s *GetOrderInfoTooManyRequestsHeaders) GetResponse() GetOrderInfoTooManyRequests {
	return s.Response
}

// SetRetryAfter sets the value of RetryAfter.
func (s *GetOrderInfoTooManyRequestsHeaders) SetRetryAfter(val OptInt) {
	s.RetryAfter = val
}

// SetResponse sets the value of Response.
func (s *GetOrderInfoTooManyRequestsHeaders) SetResponse(val GetOrderInfoTooManyRequests) {
	s.Response = val
}

func (*GetOrderInfoTooManyRequestsHeaders) getOrderInfoRes() {}

// NewOptFloat32 returns new OptFloat32 with value set to v.
func NewOptFloat32(v float32) OptFloat32 {
	return OptFloat32{
		Value: v,
		Set:   true,
	}
}

// OptFloat32 is optional float32.
type OptFloat32 struct {
	Value float32
	Set   bool
}

// IsSet returns true if OptFloat32 was set.
func (o OptFloat32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat32) Reset() {
	var v float32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat32) SetTo(v float32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat32) Get() (v float32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat32) Or(d float32) float32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Статус расчета начисления.
// Ref: #/components/schemas/order_status
type OrderStatus string

const (
	OrderStatusREGISTERED OrderStatus = "REGISTERED"
	OrderStatusINVALID    OrderStatus = "INVALID"
	OrderStatusPROCESSING OrderStatus = "PROCESSING"
	OrderStatusPROCESSED  OrderStatus = "PROCESSED"
)

// AllValues returns all OrderStatus values.
func (OrderStatus) AllValues() []OrderStatus {
	return []OrderStatus{
		OrderStatusREGISTERED,
		OrderStatusINVALID,
		OrderStatusPROCESSING,
		OrderStatusPROCESSED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderStatus) MarshalText() ([]byte, error) {
	switch s {
	case OrderStatusREGISTERED:
		return []byte(s), nil
	case OrderStatusINVALID:
		return []byte(s), nil
	case OrderStatusPROCESSING:
		return []byte(s), nil
	case OrderStatusPROCESSED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderStatus) UnmarshalText(data []byte) error {
	switch OrderStatus(data) {
	case OrderStatusREGISTERED:
		*s = OrderStatusREGISTERED
		return nil
	case OrderStatusINVALID:
		*s = OrderStatusINVALID
		return nil
	case OrderStatusPROCESSING:
		*s = OrderStatusPROCESSING
		return nil
	case OrderStatusPROCESSED:
		*s = OrderStatusPROCESSED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
