// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/delyke/gophermat_bonus_system/internal/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// AccrualWorker is an autogenerated mock type for the AccrualWorker type
type AccrualWorker struct {
	mock.Mock
}

type AccrualWorker_Expecter struct {
	mock *mock.Mock
}

func (_m *AccrualWorker) EXPECT() *AccrualWorker_Expecter {
	return &AccrualWorker_Expecter{mock: &_m.Mock}
}

// Bootstrap provides a mock function with given fields: ctx
func (_m *AccrualWorker) Bootstrap(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Bootstrap")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AccrualWorker_Bootstrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bootstrap'
type AccrualWorker_Bootstrap_Call struct {
	*mock.Call
}

// Bootstrap is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AccrualWorker_Expecter) Bootstrap(ctx interface{}) *AccrualWorker_Bootstrap_Call {
	return &AccrualWorker_Bootstrap_Call{Call: _e.mock.On("Bootstrap", ctx)}
}

func (_c *AccrualWorker_Bootstrap_Call) Run(run func(ctx context.Context)) *AccrualWorker_Bootstrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AccrualWorker_Bootstrap_Call) Return(_a0 error) *AccrualWorker_Bootstrap_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AccrualWorker_Bootstrap_Call) RunAndReturn(run func(context.Context) error) *AccrualWorker_Bootstrap_Call {
	_c.Call.Return(run)
	return _c
}

// Enqueue provides a mock function with given fields: job
func (_m *AccrualWorker) Enqueue(job model.OrderJob) {
	_m.Called(job)
}

// AccrualWorker_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type AccrualWorker_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - job model.OrderJob
func (_e *AccrualWorker_Expecter) Enqueue(job interface{}) *AccrualWorker_Enqueue_Call {
	return &AccrualWorker_Enqueue_Call{Call: _e.mock.On("Enqueue", job)}
}

func (_c *AccrualWorker_Enqueue_Call) Run(run func(job model.OrderJob)) *AccrualWorker_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.OrderJob))
	})
	return _c
}

func (_c *AccrualWorker_Enqueue_Call) Return() *AccrualWorker_Enqueue_Call {
	_c.Call.Return()
	return _c
}

func (_c *AccrualWorker_Enqueue_Call) RunAndReturn(run func(model.OrderJob)) *AccrualWorker_Enqueue_Call {
	_c.Run(run)
	return _c
}

// EnqueueLater provides a mock function with given fields: job, d
func (_m *AccrualWorker) EnqueueLater(job model.OrderJob, d time.Duration) {
	_m.Called(job, d)
}

// AccrualWorker_EnqueueLater_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueLater'
type AccrualWorker_EnqueueLater_Call struct {
	*mock.Call
}

// EnqueueLater is a helper method to define mock.On call
//   - job model.OrderJob
//   - d time.Duration
func (_e *AccrualWorker_Expecter) EnqueueLater(job interface{}, d interface{}) *AccrualWorker_EnqueueLater_Call {
	return &AccrualWorker_EnqueueLater_Call{Call: _e.mock.On("EnqueueLater", job, d)}
}

func (_c *AccrualWorker_EnqueueLater_Call) Run(run func(job model.OrderJob, d time.Duration)) *AccrualWorker_EnqueueLater_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.OrderJob), args[1].(time.Duration))
	})
	return _c
}

func (_c *AccrualWorker_EnqueueLater_Call) Return() *AccrualWorker_EnqueueLater_Call {
	_c.Call.Return()
	return _c
}

func (_c *AccrualWorker_EnqueueLater_Call) RunAndReturn(run func(model.OrderJob, time.Duration)) *AccrualWorker_EnqueueLater_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *AccrualWorker) Stop() {
	_m.Called()
}

// AccrualWorker_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type AccrualWorker_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *AccrualWorker_Expecter) Stop() *AccrualWorker_Stop_Call {
	return &AccrualWorker_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *AccrualWorker_Stop_Call) Run(run func()) *AccrualWorker_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AccrualWorker_Stop_Call) Return() *AccrualWorker_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *AccrualWorker_Stop_Call) RunAndReturn(run func()) *AccrualWorker_Stop_Call {
	_c.Run(run)
	return _c
}

// NewAccrualWorker creates a new instance of AccrualWorker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccrualWorker(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccrualWorker {
	mock := &AccrualWorker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
