// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/delyke/gophermat_bonus_system/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// WithdrawalService is an autogenerated mock type for the WithdrawalService type
type WithdrawalService struct {
	mock.Mock
}

type WithdrawalService_Expecter struct {
	mock *mock.Mock
}

func (_m *WithdrawalService) EXPECT() *WithdrawalService_Expecter {
	return &WithdrawalService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, orderID, sum
func (_m *WithdrawalService) Create(ctx context.Context, orderID []byte, sum float64) error {
	ret := _m.Called(ctx, orderID, sum)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, float64) error); ok {
		r0 = rf(ctx, orderID, sum)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithdrawalService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type WithdrawalService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID []byte
//   - sum float64
func (_e *WithdrawalService_Expecter) Create(ctx interface{}, orderID interface{}, sum interface{}) *WithdrawalService_Create_Call {
	return &WithdrawalService_Create_Call{Call: _e.mock.On("Create", ctx, orderID, sum)}
}

func (_c *WithdrawalService_Create_Call) Run(run func(ctx context.Context, orderID []byte, sum float64)) *WithdrawalService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(float64))
	})
	return _c
}

func (_c *WithdrawalService_Create_Call) Return(_a0 error) *WithdrawalService_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WithdrawalService_Create_Call) RunAndReturn(run func(context.Context, []byte, float64) error) *WithdrawalService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetList provides a mock function with given fields: ctx
func (_m *WithdrawalService) GetList(ctx context.Context) ([]*model.Withdrawal, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 []*model.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.Withdrawal, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Withdrawal); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Withdrawal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithdrawalService_GetList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetList'
type WithdrawalService_GetList_Call struct {
	*mock.Call
}

// GetList is a helper method to define mock.On call
//   - ctx context.Context
func (_e *WithdrawalService_Expecter) GetList(ctx interface{}) *WithdrawalService_GetList_Call {
	return &WithdrawalService_GetList_Call{Call: _e.mock.On("GetList", ctx)}
}

func (_c *WithdrawalService_GetList_Call) Run(run func(ctx context.Context)) *WithdrawalService_GetList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *WithdrawalService_GetList_Call) Return(_a0 []*model.Withdrawal, _a1 error) *WithdrawalService_GetList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WithdrawalService_GetList_Call) RunAndReturn(run func(context.Context) ([]*model.Withdrawal, error)) *WithdrawalService_GetList_Call {
	_c.Call.Return(run)
	return _c
}

// NewWithdrawalService creates a new instance of WithdrawalService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWithdrawalService(t interface {
	mock.TestingT
	Cleanup(func())
}) *WithdrawalService {
	mock := &WithdrawalService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
