// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	service "github.com/delyke/gophermat_bonus_system/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// BonusService is an autogenerated mock type for the BonusService type
type BonusService struct {
	mock.Mock
}

type BonusService_Expecter struct {
	mock *mock.Mock
}

func (_m *BonusService) EXPECT() *BonusService_Expecter {
	return &BonusService_Expecter{mock: &_m.Mock}
}

// Orders provides a mock function with no fields
func (_m *BonusService) Orders() service.OrderService {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Orders")
	}

	var r0 service.OrderService
	if rf, ok := ret.Get(0).(func() service.OrderService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.OrderService)
		}
	}

	return r0
}

// BonusService_Orders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Orders'
type BonusService_Orders_Call struct {
	*mock.Call
}

// Orders is a helper method to define mock.On call
func (_e *BonusService_Expecter) Orders() *BonusService_Orders_Call {
	return &BonusService_Orders_Call{Call: _e.mock.On("Orders")}
}

func (_c *BonusService_Orders_Call) Run(run func()) *BonusService_Orders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BonusService_Orders_Call) Return(_a0 service.OrderService) *BonusService_Orders_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BonusService_Orders_Call) RunAndReturn(run func() service.OrderService) *BonusService_Orders_Call {
	_c.Call.Return(run)
	return _c
}

// Users provides a mock function with no fields
func (_m *BonusService) Users() service.UserService {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Users")
	}

	var r0 service.UserService
	if rf, ok := ret.Get(0).(func() service.UserService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.UserService)
		}
	}

	return r0
}

// BonusService_Users_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Users'
type BonusService_Users_Call struct {
	*mock.Call
}

// Users is a helper method to define mock.On call
func (_e *BonusService_Expecter) Users() *BonusService_Users_Call {
	return &BonusService_Users_Call{Call: _e.mock.On("Users")}
}

func (_c *BonusService_Users_Call) Run(run func()) *BonusService_Users_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BonusService_Users_Call) Return(_a0 service.UserService) *BonusService_Users_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BonusService_Users_Call) RunAndReturn(run func() service.UserService) *BonusService_Users_Call {
	_c.Call.Return(run)
	return _c
}

// Withdrawals provides a mock function with no fields
func (_m *BonusService) Withdrawals() service.WithdrawalService {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Withdrawals")
	}

	var r0 service.WithdrawalService
	if rf, ok := ret.Get(0).(func() service.WithdrawalService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.WithdrawalService)
		}
	}

	return r0
}

// BonusService_Withdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdrawals'
type BonusService_Withdrawals_Call struct {
	*mock.Call
}

// Withdrawals is a helper method to define mock.On call
func (_e *BonusService_Expecter) Withdrawals() *BonusService_Withdrawals_Call {
	return &BonusService_Withdrawals_Call{Call: _e.mock.On("Withdrawals")}
}

func (_c *BonusService_Withdrawals_Call) Run(run func()) *BonusService_Withdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BonusService_Withdrawals_Call) Return(_a0 service.WithdrawalService) *BonusService_Withdrawals_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BonusService_Withdrawals_Call) RunAndReturn(run func() service.WithdrawalService) *BonusService_Withdrawals_Call {
	_c.Call.Return(run)
	return _c
}

// NewBonusService creates a new instance of BonusService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBonusService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BonusService {
	mock := &BonusService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
