// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/delyke/gophermat_bonus_system/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

type OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderService) EXPECT() *OrderService_Expecter {
	return &OrderService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, orderID
func (_m *OrderService) Create(ctx context.Context, orderID []byte) (string, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) (string, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte) string); ok {
		r0 = rf(ctx, orderID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OrderService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID []byte
func (_e *OrderService_Expecter) Create(ctx interface{}, orderID interface{}) *OrderService_Create_Call {
	return &OrderService_Create_Call{Call: _e.mock.On("Create", ctx, orderID)}
}

func (_c *OrderService_Create_Call) Run(run func(ctx context.Context, orderID []byte)) *OrderService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *OrderService_Create_Call) Return(_a0 string, _a1 error) *OrderService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_Create_Call) RunAndReturn(run func(context.Context, []byte) (string, error)) *OrderService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUploadedDesc provides a mock function with given fields: ctx
func (_m *OrderService) ListByUploadedDesc(ctx context.Context) ([]*model.Order, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListByUploadedDesc")
	}

	var r0 []*model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.Order, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Order); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_ListByUploadedDesc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUploadedDesc'
type OrderService_ListByUploadedDesc_Call struct {
	*mock.Call
}

// ListByUploadedDesc is a helper method to define mock.On call
//   - ctx context.Context
func (_e *OrderService_Expecter) ListByUploadedDesc(ctx interface{}) *OrderService_ListByUploadedDesc_Call {
	return &OrderService_ListByUploadedDesc_Call{Call: _e.mock.On("ListByUploadedDesc", ctx)}
}

func (_c *OrderService_ListByUploadedDesc_Call) Run(run func(ctx context.Context)) *OrderService_ListByUploadedDesc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *OrderService_ListByUploadedDesc_Call) Return(_a0 []*model.Order, _a1 error) *OrderService_ListByUploadedDesc_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_ListByUploadedDesc_Call) RunAndReturn(run func(context.Context) ([]*model.Order, error)) *OrderService_ListByUploadedDesc_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
