// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// TokenIssuer is an autogenerated mock type for the TokenIssuer type
type TokenIssuer struct {
	mock.Mock
}

type TokenIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenIssuer) EXPECT() *TokenIssuer_Expecter {
	return &TokenIssuer_Expecter{mock: &_m.Mock}
}

// IssueAccessToken provides a mock function with given fields: userUUID, login, ttl
func (_m *TokenIssuer) IssueAccessToken(userUUID string, login string, ttl time.Duration) (string, error) {
	ret := _m.Called(userUUID, login, ttl)

	if len(ret) == 0 {
		panic("no return value specified for IssueAccessToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, time.Duration) (string, error)); ok {
		return rf(userUUID, login, ttl)
	}
	if rf, ok := ret.Get(0).(func(string, string, time.Duration) string); ok {
		r0 = rf(userUUID, login, ttl)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, time.Duration) error); ok {
		r1 = rf(userUUID, login, ttl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenIssuer_IssueAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueAccessToken'
type TokenIssuer_IssueAccessToken_Call struct {
	*mock.Call
}

// IssueAccessToken is a helper method to define mock.On call
//   - userUUID string
//   - login string
//   - ttl time.Duration
func (_e *TokenIssuer_Expecter) IssueAccessToken(userUUID interface{}, login interface{}, ttl interface{}) *TokenIssuer_IssueAccessToken_Call {
	return &TokenIssuer_IssueAccessToken_Call{Call: _e.mock.On("IssueAccessToken", userUUID, login, ttl)}
}

func (_c *TokenIssuer_IssueAccessToken_Call) Run(run func(userUUID string, login string, ttl time.Duration)) *TokenIssuer_IssueAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *TokenIssuer_IssueAccessToken_Call) Return(_a0 string, _a1 error) *TokenIssuer_IssueAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenIssuer_IssueAccessToken_Call) RunAndReturn(run func(string, string, time.Duration) (string, error)) *TokenIssuer_IssueAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenIssuer creates a new instance of TokenIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenIssuer {
	mock := &TokenIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
