// Code generated by ogen, DO NOT EDIT.

package bonus_v1

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleJwtCookieAuth handles JwtCookieAuth security.
	// JWT access token, передаётся в cookie `access_token` (HttpOnly).
	HandleJwtCookieAuth(ctx context.Context, operationName OperationName, t JwtCookieAuth) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

var operationRolesJwtCookieAuth = map[string][]string{
	BalanceWithdrawalOperation:   []string{},
	GetOrdersNumberListOperation: []string{},
	GetUserBalanceOperation:      []string{},
	GetWithdrawalsOperation:      []string{},
	OrderNumberLoadOperation:     []string{},
}

func (s *Server) securityJwtCookieAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t JwtCookieAuth
	const parameterName = "access_token"
	var value string
	switch cookie, err := req.Cookie(parameterName); {
	case err == nil: // if NO error
		value = cookie.Value
	case errors.Is(err, http.ErrNoCookie):
		return ctx, false, nil
	default:
		return nil, false, errors.Wrap(err, "get cookie value")
	}
	t.APIKey = value
	t.Roles = operationRolesJwtCookieAuth[operationName]
	rctx, err := s.sec.HandleJwtCookieAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// JwtCookieAuth provides JwtCookieAuth security value.
	// JWT access token, передаётся в cookie `access_token` (HttpOnly).
	JwtCookieAuth(ctx context.Context, operationName OperationName) (JwtCookieAuth, error)
}

func (s *Client) securityJwtCookieAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.JwtCookieAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"JwtCookieAuth\"")
	}
	req.AddCookie(&http.Cookie{
		Name:  "access_token",
		Value: t.APIKey,
	})
	return nil
}
