// Code generated by ogen, DO NOT EDIT.
package bonus_v1

type BalanceWithdrawalRes interface {
	balanceWithdrawalRes()
}

type GetOrdersNumberListRes interface {
	getOrdersNumberListRes()
}

type GetUserBalanceRes interface {
	getUserBalanceRes()
}

type GetWithdrawalsRes interface {
	getWithdrawalsRes()
}

type LoginUserRes interface {
	loginUserRes()
}

type OrderNumberLoadRes interface {
	orderNumberLoadRes()
}

type RegisterUserRes interface {
	registerUserRes()
}
