// Code generated by ogen, DO NOT EDIT.

package bonus_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// BalanceWithdrawal implements BalanceWithdrawal operation.
	//
	// Запрос на списание средств.
	//
	// POST /api/user/balance/withdraw
	BalanceWithdrawal(ctx context.Context, req *BalanceWithdrawalRequest) (BalanceWithdrawalRes, error)
	// GetOrdersNumberList implements GetOrdersNumberList operation.
	//
	// Получение списка загруженных номеров заказов.
	//
	// GET /api/user/orders
	GetOrdersNumberList(ctx context.Context) (GetOrdersNumberListRes, error)
	// GetUserBalance implements GetUserBalance operation.
	//
	// Получение текущего баланса пользователя.
	//
	// GET /api/user/balance
	GetUserBalance(ctx context.Context) (GetUserBalanceRes, error)
	// GetWithdrawals implements GetWithdrawals operation.
	//
	// Получение информации о выводе средств.
	//
	// GET /api/user/withdrawals
	GetWithdrawals(ctx context.Context) (GetWithdrawalsRes, error)
	// LoginUser implements LoginUser operation.
	//
	// Аутентификация пользователя.
	//
	// POST /api/user/login
	LoginUser(ctx context.Context, req *LoginRequest) (LoginUserRes, error)
	// OrderNumberLoad implements OrderNumberLoad operation.
	//
	// Загрузка номера заказа.
	//
	// POST /api/user/orders
	OrderNumberLoad(ctx context.Context, req OrderNumberLoadReq) (OrderNumberLoadRes, error)
	// RegisterUser implements RegisterUser operation.
	//
	// Регистрация пользователя.
	//
	// POST /api/user/register
	RegisterUser(ctx context.Context, req *RegisterRequest) (RegisterUserRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
