// Code generated by ogen, DO NOT EDIT.

package bonus_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// BalanceWithdrawal implements BalanceWithdrawal operation.
//
// Запрос на списание средств.
//
// POST /api/user/balance/withdraw
func (UnimplementedHandler) BalanceWithdrawal(ctx context.Context, req *BalanceWithdrawalRequest) (r BalanceWithdrawalRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrdersNumberList implements GetOrdersNumberList operation.
//
// Получение списка загруженных номеров заказов.
//
// GET /api/user/orders
func (UnimplementedHandler) GetOrdersNumberList(ctx context.Context) (r GetOrdersNumberListRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserBalance implements GetUserBalance operation.
//
// Получение текущего баланса пользователя.
//
// GET /api/user/balance
func (UnimplementedHandler) GetUserBalance(ctx context.Context) (r GetUserBalanceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWithdrawals implements GetWithdrawals operation.
//
// Получение информации о выводе средств.
//
// GET /api/user/withdrawals
func (UnimplementedHandler) GetWithdrawals(ctx context.Context) (r GetWithdrawalsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// LoginUser implements LoginUser operation.
//
// Аутентификация пользователя.
//
// POST /api/user/login
func (UnimplementedHandler) LoginUser(ctx context.Context, req *LoginRequest) (r LoginUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrderNumberLoad implements OrderNumberLoad operation.
//
// Загрузка номера заказа.
//
// POST /api/user/orders
func (UnimplementedHandler) OrderNumberLoad(ctx context.Context, req OrderNumberLoadReq) (r OrderNumberLoadRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RegisterUser implements RegisterUser operation.
//
// Регистрация пользователя.
//
// POST /api/user/register
func (UnimplementedHandler) RegisterUser(ctx context.Context, req *RegisterRequest) (r RegisterUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *GenericErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *GenericErrorStatusCode) {
	r = new(GenericErrorStatusCode)
	return r
}
