// Code generated by ogen, DO NOT EDIT.

package bonus_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	BalanceWithdrawalOperation   OperationName = "BalanceWithdrawal"
	GetOrdersNumberListOperation OperationName = "GetOrdersNumberList"
	GetUserBalanceOperation      OperationName = "GetUserBalance"
	GetWithdrawalsOperation      OperationName = "GetWithdrawals"
	LoginUserOperation           OperationName = "LoginUser"
	OrderNumberLoadOperation     OperationName = "OrderNumberLoad"
	RegisterUserOperation        OperationName = "RegisterUser"
)
