// Code generated by ogen, DO NOT EDIT.

package bonus_v1

import (
	"io"
	"time"

	"github.com/go-faster/errors"
)

// Ref: #/components/schemas/balance_response
type BalanceResponse struct {
	// Данные о текущей сумме баллов лояльности.
	Current float32 `json:"current"`
	// Сумма использованных за весь период регистрации
	// баллов.
	Withdrawn float32 `json:"withdrawn"`
}

// GetCurrent returns the value of Current.
func (s *BalanceResponse) GetCurrent() float32 {
	return s.Current
}

// GetWithdrawn returns the value of Withdrawn.
func (s *BalanceResponse) GetWithdrawn() float32 {
	return s.Withdrawn
}

// SetCurrent sets the value of Current.
func (s *BalanceResponse) SetCurrent(val float32) {
	s.Current = val
}

// SetWithdrawn sets the value of Withdrawn.
func (s *BalanceResponse) SetWithdrawn(val float32) {
	s.Withdrawn = val
}

func (*BalanceResponse) getUserBalanceRes() {}

// BalanceWithdrawalInternalServerError is response for BalanceWithdrawal operation.
type BalanceWithdrawalInternalServerError struct{}

func (*BalanceWithdrawalInternalServerError) balanceWithdrawalRes() {}

// BalanceWithdrawalOK is response for BalanceWithdrawal operation.
type BalanceWithdrawalOK struct{}

func (*BalanceWithdrawalOK) balanceWithdrawalRes() {}

// BalanceWithdrawalPaymentRequired is response for BalanceWithdrawal operation.
type BalanceWithdrawalPaymentRequired struct{}

func (*BalanceWithdrawalPaymentRequired) balanceWithdrawalRes() {}

// Ref: #/components/schemas/balance_withdrawal_request
type BalanceWithdrawalRequest struct {
	// Номер заказа.
	Order string `json:"order"`
	// Сумма баллов к списанию в счет оплаты.
	Sum float32 `json:"sum"`
}

// GetOrder returns the value of Order.
func (s *BalanceWithdrawalRequest) GetOrder() string {
	return s.Order
}

// GetSum returns the value of Sum.
func (s *BalanceWithdrawalRequest) GetSum() float32 {
	return s.Sum
}

// SetOrder sets the value of Order.
func (s *BalanceWithdrawalRequest) SetOrder(val string) {
	s.Order = val
}

// SetSum sets the value of Sum.
func (s *BalanceWithdrawalRequest) SetSum(val float32) {
	s.Sum = val
}

// BalanceWithdrawalUnauthorized is response for BalanceWithdrawal operation.
type BalanceWithdrawalUnauthorized struct{}

func (*BalanceWithdrawalUnauthorized) balanceWithdrawalRes() {}

// BalanceWithdrawalUnprocessableEntity is response for BalanceWithdrawal operation.
type BalanceWithdrawalUnprocessableEntity struct{}

func (*BalanceWithdrawalUnprocessableEntity) balanceWithdrawalRes() {}

// GetOrdersNumberListInternalServerError is response for GetOrdersNumberList operation.
type GetOrdersNumberListInternalServerError struct{}

func (*GetOrdersNumberListInternalServerError) getOrdersNumberListRes() {}

// GetOrdersNumberListNoContent is response for GetOrdersNumberList operation.
type GetOrdersNumberListNoContent struct{}

func (*GetOrdersNumberListNoContent) getOrdersNumberListRes() {}

type GetOrdersNumberListResponse []OrderDto

func (*GetOrdersNumberListResponse) getOrdersNumberListRes() {}

// GetOrdersNumberListUnauthorized is response for GetOrdersNumberList operation.
type GetOrdersNumberListUnauthorized struct{}

func (*GetOrdersNumberListUnauthorized) getOrdersNumberListRes() {}

// GetUserBalanceInternalServerError is response for GetUserBalance operation.
type GetUserBalanceInternalServerError struct{}

func (*GetUserBalanceInternalServerError) getUserBalanceRes() {}

// GetUserBalanceUnauthorized is response for GetUserBalance operation.
type GetUserBalanceUnauthorized struct{}

func (*GetUserBalanceUnauthorized) getUserBalanceRes() {}

// GetWithdrawalsInternalServerError is response for GetWithdrawals operation.
type GetWithdrawalsInternalServerError struct{}

func (*GetWithdrawalsInternalServerError) getWithdrawalsRes() {}

// GetWithdrawalsNoContent is response for GetWithdrawals operation.
type GetWithdrawalsNoContent struct{}

func (*GetWithdrawalsNoContent) getWithdrawalsRes() {}

type GetWithdrawalsResponse []WithdrawalDto

func (*GetWithdrawalsResponse) getWithdrawalsRes() {}

// GetWithdrawalsUnauthorized is response for GetWithdrawals operation.
type GetWithdrawalsUnauthorized struct{}

func (*GetWithdrawalsUnauthorized) getWithdrawalsRes() {}

type JwtCookieAuth struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *JwtCookieAuth) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *JwtCookieAuth) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *JwtCookieAuth) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *JwtCookieAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/login_request
type LoginRequest struct {
	// Логин пользователя.
	Login string `json:"login"`
	// Пароль пользователя.
	Password string `json:"password"`
}

// GetLogin returns the value of Login.
func (s *LoginRequest) GetLogin() string {
	return s.Login
}

// GetPassword returns the value of Password.
func (s *LoginRequest) GetPassword() string {
	return s.Password
}

// SetLogin sets the value of Login.
func (s *LoginRequest) SetLogin(val string) {
	s.Login = val
}

// SetPassword sets the value of Password.
func (s *LoginRequest) SetPassword(val string) {
	s.Password = val
}

// LoginUserBadRequest is response for LoginUser operation.
type LoginUserBadRequest struct{}

func (*LoginUserBadRequest) loginUserRes() {}

// LoginUserInternalServerError is response for LoginUser operation.
type LoginUserInternalServerError struct{}

func (*LoginUserInternalServerError) loginUserRes() {}

// LoginUserOK is response for LoginUser operation.
type LoginUserOK struct {
	SetCookie OptString
}

// GetSetCookie returns the value of SetCookie.
func (s *LoginUserOK) GetSetCookie() OptString {
	return s.SetCookie
}

// SetSetCookie sets the value of SetCookie.
func (s *LoginUserOK) SetSetCookie(val OptString) {
	s.SetCookie = val
}

func (*LoginUserOK) loginUserRes() {}

// LoginUserUnauthorized is response for LoginUser operation.
type LoginUserUnauthorized struct{}

func (*LoginUserUnauthorized) loginUserRes() {}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFloat32 returns new OptFloat32 with value set to v.
func NewOptFloat32(v float32) OptFloat32 {
	return OptFloat32{
		Value: v,
		Set:   true,
	}
}

// OptFloat32 is optional float32.
type OptFloat32 struct {
	Value float32
	Set   bool
}

// IsSet returns true if OptFloat32 was set.
func (o OptFloat32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat32) Reset() {
	var v float32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat32) SetTo(v float32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat32) Get() (v float32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat32) Or(d float32) float32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/order_dto
type OrderDto struct {
	// Номер заказа.
	Number string      `json:"number"`
	Status OrderStatus `json:"status"`
	// Сумма начисления.
	Accrual OptFloat32 `json:"accrual"`
	// Дата загрузки заказа (RFC3339).
	UploadedAt time.Time `json:"uploaded_at"`
}

// GetNumber returns the value of Number.
func (s *OrderDto) GetNumber() string {
	return s.Number
}

// GetStatus returns the value of Status.
func (s *OrderDto) GetStatus() OrderStatus {
	return s.Status
}

// GetAccrual returns the value of Accrual.
func (s *OrderDto) GetAccrual() OptFloat32 {
	return s.Accrual
}

// GetUploadedAt returns the value of UploadedAt.
func (s *OrderDto) GetUploadedAt() time.Time {
	return s.UploadedAt
}

// SetNumber sets the value of Number.
func (s *OrderDto) SetNumber(val string) {
	s.Number = val
}

// SetStatus sets the value of Status.
func (s *OrderDto) SetStatus(val OrderStatus) {
	s.Status = val
}

// SetAccrual sets the value of Accrual.
func (s *OrderDto) SetAccrual(val OptFloat32) {
	s.Accrual = val
}

// SetUploadedAt sets the value of UploadedAt.
func (s *OrderDto) SetUploadedAt(val time.Time) {
	s.UploadedAt = val
}

// OrderNumberLoadAccepted is response for OrderNumberLoad operation.
type OrderNumberLoadAccepted struct{}

func (*OrderNumberLoadAccepted) orderNumberLoadRes() {}

// OrderNumberLoadBadRequest is response for OrderNumberLoad operation.
type OrderNumberLoadBadRequest struct{}

func (*OrderNumberLoadBadRequest) orderNumberLoadRes() {}

// OrderNumberLoadConflict is response for OrderNumberLoad operation.
type OrderNumberLoadConflict struct{}

func (*OrderNumberLoadConflict) orderNumberLoadRes() {}

// OrderNumberLoadInternalServerError is response for OrderNumberLoad operation.
type OrderNumberLoadInternalServerError struct{}

func (*OrderNumberLoadInternalServerError) orderNumberLoadRes() {}

// OrderNumberLoadOK is response for OrderNumberLoad operation.
type OrderNumberLoadOK struct{}

func (*OrderNumberLoadOK) orderNumberLoadRes() {}

// Номер заказа, состоящий только из цифр.
// Ref: #/components/schemas/load_order_number_request
type OrderNumberLoadReq struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s OrderNumberLoadReq) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

// OrderNumberLoadUnauthorized is response for OrderNumberLoad operation.
type OrderNumberLoadUnauthorized struct{}

func (*OrderNumberLoadUnauthorized) orderNumberLoadRes() {}

// OrderNumberLoadUnprocessableEntity is response for OrderNumberLoad operation.
type OrderNumberLoadUnprocessableEntity struct{}

func (*OrderNumberLoadUnprocessableEntity) orderNumberLoadRes() {}

// Статус заказа.
// Ref: #/components/schemas/order_status
type OrderStatus string

const (
	OrderStatusNEW        OrderStatus = "NEW"
	OrderStatusPROCESSING OrderStatus = "PROCESSING"
	OrderStatusINVALID    OrderStatus = "INVALID"
	OrderStatusPROCESSED  OrderStatus = "PROCESSED"
)

// AllValues returns all OrderStatus values.
func (OrderStatus) AllValues() []OrderStatus {
	return []OrderStatus{
		OrderStatusNEW,
		OrderStatusPROCESSING,
		OrderStatusINVALID,
		OrderStatusPROCESSED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderStatus) MarshalText() ([]byte, error) {
	switch s {
	case OrderStatusNEW:
		return []byte(s), nil
	case OrderStatusPROCESSING:
		return []byte(s), nil
	case OrderStatusINVALID:
		return []byte(s), nil
	case OrderStatusPROCESSED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderStatus) UnmarshalText(data []byte) error {
	switch OrderStatus(data) {
	case OrderStatusNEW:
		*s = OrderStatusNEW
		return nil
	case OrderStatusPROCESSING:
		*s = OrderStatusPROCESSING
		return nil
	case OrderStatusINVALID:
		*s = OrderStatusINVALID
		return nil
	case OrderStatusPROCESSED:
		*s = OrderStatusPROCESSED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/register_request
type RegisterRequest struct {
	// Логин пользователя.
	Login string `json:"login"`
	// Пароль пользователя.
	Password string `json:"password"`
}

// GetLogin returns the value of Login.
func (s *RegisterRequest) GetLogin() string {
	return s.Login
}

// GetPassword returns the value of Password.
func (s *RegisterRequest) GetPassword() string {
	return s.Password
}

// SetLogin sets the value of Login.
func (s *RegisterRequest) SetLogin(val string) {
	s.Login = val
}

// SetPassword sets the value of Password.
func (s *RegisterRequest) SetPassword(val string) {
	s.Password = val
}

// RegisterUserBadRequest is response for RegisterUser operation.
type RegisterUserBadRequest struct{}

func (*RegisterUserBadRequest) registerUserRes() {}

// RegisterUserConflict is response for RegisterUser operation.
type RegisterUserConflict struct{}

func (*RegisterUserConflict) registerUserRes() {}

// RegisterUserInternalServerError is response for RegisterUser operation.
type RegisterUserInternalServerError struct{}

func (*RegisterUserInternalServerError) registerUserRes() {}

// RegisterUserOK is response for RegisterUser operation.
type RegisterUserOK struct {
	SetCookie OptString
}

// GetSetCookie returns the value of SetCookie.
func (s *RegisterUserOK) GetSetCookie() OptString {
	return s.SetCookie
}

// SetSetCookie sets the value of SetCookie.
func (s *RegisterUserOK) SetSetCookie(val OptString) {
	s.SetCookie = val
}

func (*RegisterUserOK) registerUserRes() {}

// Ref: #/components/schemas/withdrawal_dto
type WithdrawalDto struct {
	// Номер заказа.
	Order string `json:"order"`
	// Сумма вывода.
	Sum float32 `json:"sum"`
	// Дата обработки запроса (RFC3339).
	ProcessedAt OptDateTime `json:"processed_at"`
}

// GetOrder returns the value of Order.
func (s *WithdrawalDto) GetOrder() string {
	return s.Order
}

// GetSum returns the value of Sum.
func (s *WithdrawalDto) GetSum() float32 {
	return s.Sum
}

// GetProcessedAt returns the value of ProcessedAt.
func (s *WithdrawalDto) GetProcessedAt() OptDateTime {
	return s.ProcessedAt
}

// SetOrder sets the value of Order.
func (s *WithdrawalDto) SetOrder(val string) {
	s.Order = val
}

// SetSum sets the value of Sum.
func (s *WithdrawalDto) SetSum(val float32) {
	s.Sum = val
}

// SetProcessedAt sets the value of ProcessedAt.
func (s *WithdrawalDto) SetProcessedAt(val OptDateTime) {
	s.ProcessedAt = val
}
